# Generated by Django 3.2.5 on 2021-07-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
