# Generated by Django 3.2.5 on 2021-07-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='status',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
